// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Geolocations struct {
	ID          int64        `json:"id"`
	CountryCode string       `json:"country_code"`
	CityName    string       `json:"city_name"`
	IpAddress   string       `json:"ip_address"`
	Latitude    string       `json:"latitude"`
	Longitude   string       `json:"longitude"`
	Mystery     string       `json:"mystery"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
