// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Geolocations struct {
	ID          int64          `json:"id"`
	CountryCode sql.NullString `json:"country_code"`
	CityName    sql.NullString `json:"city_name"`
	IpAddress   sql.NullString `json:"ip_address"`
	Latitude    sql.NullString `json:"latitude"`
	Longitude   sql.NullString `json:"longitude"`
	Mystery     sql.NullString `json:"mystery"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
