// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateGeolocation(ctx context.Context, arg CreateGeolocationParams) (Geolocations, error)
	GetGeolocation(ctx context.Context, ipAddress string) (Geolocations, error)
}

var _ Querier = (*Queries)(nil)
